language: cpp
compiler: gcc
dist: xenial

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j
  - make test
